In [12]:
import pandas as pd
df = pd.read_csv('airportss.csv')
df

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.947733,-151.692524,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,506791,00AN,small_airport,Katmai Lodge Airport,59.093287,-156.456699,80.0,NaN,US,US-AK,King Salmon,no,00AN,NaN,00AN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76317,46378,ZZ-0001,heliport,Sealand Helipad,51.894444,1.482500,40.0,EU,GB,GB-ENG,Sealand,no,NaN,NaN,NaN,http://www.sealandgov.org/,https://en.wikipedia.org/wiki/Principality_of_...,Roughs Tower Helipad
76318,307326,ZZ-0002,small_airport,Glorioso Islands Airstrip,-11.584278,47.296389,11.0,AF,TF,TF-U-A,Grande Glorieuse,no,NaN,NaN,NaN,NaN,NaN,NaN
76319,346788,ZZ-0003,small_airport,Fainting Goat Airport,32.110587,-97.356312,690.0,NaN,US,US-TX,Blum,no,87TX,NaN,87TX,NaN,NaN,NaN
76320,342102,ZZZW,closed,Scandium City Heliport,69.355287,-138.939310,4.0,NaN,CA,CA-YT,(Old) Scandium City,no,NaN,NaN,NaN,NaN,NaN,"ZZZW, ZZZW, ZYW, YK96"
76321,313629,ZZZZ,small_airport,Satsuma Iōjima Airport,30.784722,130.270556,338.0,AS,JP,JP-46,Mishima,no,RJX7,NaN,RJX7,NaN,http://wikimapia.org/6705190/Satsuma-Iwo-jima-...,"SATSUMA,IWOJIMA,RJX7"

In [14]:
result = df.groupby(['iso_country', 'continent', 'type'])['type'].count().unstack(fill_value=0)
print(result)

type                   balloonport  closed  heliport  large_airport  \
iso_country continent
AD          EU                   0       1         2              0
AE          AS                   0       4       200              4
AF          AS                   0       3         8              0
AL          EU                   0       6         8              1
AM          AS                   0       4         1              1
...                            ...     ...       ...            ...
YE          AS                   0       0         6              0
YT          AF                   0       0         0              0
ZA          AF                   0      26        48              3
ZM          AF                   0       2         4              1
ZW          AF                   0       6         5              1

type                   medium_airport  seaplane_base  small_airport
iso_country continent
AD          EU                      0              0              0
AE          AS                      8              4             30
AF          AS                      9              0             58
AL          EU                      2              0              1
AM          AS                      2              0              8
...                               ...            ...            ...
YE          AS                     10              0             22
YT          AF                      1              0              0
ZA          AF                     57              0            511
ZM          AF                      8              0            110
ZW          AF                      8              0            135

[211 rows x 7 columns]

In [23]:
import pandas as pd

In [24]:
data = pd.read_csv('airportss.csv')

In [25]:
mean_elevation = data.groupby(['iso_country', 'type'])['elevation_ft'].mean().unstack()

In [26]:
print(mean_elevation)

type         balloonport       closed     heliport  large_airport  \
iso_country
AD                   NaN          NaN  3450.000000            NaN
AE                   NaN   323.500000   113.791667      93.750000
AF                   NaN  5514.333333  3198.333333            NaN
AG                   NaN          NaN    13.000000            NaN
AI                   NaN          NaN          NaN            NaN
...                  ...          ...          ...            ...
YE                   NaN          NaN    78.833333            NaN
YT                   NaN          NaN          NaN            NaN
ZA                   NaN  2681.368421  3918.428571    2001.333333
ZM                   NaN  4300.000000  2658.500000    3779.000000
ZW                   NaN  3236.500000  3014.250000    4887.000000

type         medium_airport  seaplane_base  small_airport
iso_country
AD                      NaN            NaN            NaN
AE               204.000000            0.0     104.650000
AF              3201.888889            NaN    5344.673077
AG                38.500000            NaN      15.000000
AI               127.000000            NaN            NaN
...                     ...            ...            ...
YE              1916.800000            NaN    2814.176471
YT                23.000000            NaN            NaN
ZA              2669.122807            NaN    3164.130435
ZM              3768.125000            NaN    3564.298851
ZW              3343.000000            NaN    2994.810000

[244 rows x 7 columns]

In [27]:
import pandas as pd

In [44]:
data = pd.read_csv('allCountries.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 830: invalid start byte